### ISSUE TITLE
Parameter name with spaces

### ISSUE THREAD

**Issue by felipecrs** [jenkinsci/embeddable-build-status-plugin#170]
I have a parameter like following:

```groovy
stringParam {
  trim(true)
  name('Version to install')
  defaultValue('')
  description('The version to install.')
}
```

Which I can use in Jenkinsfiles like:

```groovy
echo params.'Version to install'
```

However, I'm trying to use it as a variable in the `?subject=`, but I can't make it work. I think I tried everything already.

Any help would be appreciated.

**Comment by MarkEWaite** [comment]
I believe that the strings in the URL need to be URL encoded.

Thus:

https://ci.jenkins.io/job/Plugins/job/embeddable-build-status-plugin/job/master/lastBuild/badge/icon?subject=My%20space%20is%20mine

results in this:

[![Plugin build status](https://ci.jenkins.io/job/Plugins/job/embeddable-build-status-plugin/job/master/lastBuild/badge/icon?subject=My+space+is+mine)](https://ci.jenkins.io/job/Plugins/job/embeddable-build-status-plugin/job/master/lastBuild/)

**Comment by felipecrs** [comment]
I'm sorry, but I meant variables expansion for Jenkins build parameters and spaces in the parameter name, not spaces in the subject text itself.

**Comment by MarkEWaite** [comment]
I have no idea how you would use variable names or parameters with spaces in them.

**Comment by felipecrs** [comment]
I see. I have tried everything, but maybe this is actually not supported by the plugin.

Thanks anyway.
