### ISSUE TITLE
Build status for specific branch

### ISSUE THREAD

**Issue by ShanHuang** [jenkinsci/embeddable-build-status-plugin#21]
Hey there,

Is it possible have a place define a specific branch name which the badge status to be reflect on?

For example:
`https://jenkins.gedmin.as/buildStatus/branchName/icon`

Thanks.

**Comment by alasarr** [comment]
+1. This feature will be really nice.

**Comment by babielph** [comment]
+1 For that feature !

**Comment by gtron** [comment]
+1 It would be soooo nice and useful!

**Comment by midolo** [comment]
+1 would be awesome!

**Comment by cklosowski** [comment]
+1. Would love to see this feature.

**Comment by Skeen** [comment]
Just another +1

**Comment by aymericDD** [comment]
+1

**Comment by thomas-dee** [comment]
The next release will include ExtensionPoints for the selection of a specific `job` and `build` for the Unprotected Badge URL (`JobSelectorExtensionPoint` and `RunSelectorExtensionPoint`)

**Comment by thomas-dee** [comment]
Just released v2.0-beta1. Please refer to [](https://jenkins.io/doc/developer/publishing/releasing-experimental-updates) on to install it.

**Comment by thomas-dee** [comment]
v2.0 released
