### ISSUE TITLE
Disabled Status

### ISSUE THREAD

**Issue by jasel-lewis** [jenkinsci/embeddable-build-status-plugin#24]
I see in version 1.2, back in March of 2013, the decision was made to utilize the "Unknown" image to represent the disabled status for a build.  I would argue that the "disabled" status is a valid status in, and of, itself and should therefore not be classified as "unknown."  Would it be possible to utilize a "Disabled" image for the "disabled" status?  I agree with the decision to use the "light-gray" coloration to represent this status.

Thank you...

**Comment by thomas-dee** [comment]
Should be fixed with v2.0-beta1.

**Comment by thomas-dee** [comment]
v2.0 released
