### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by asvishnyakov** [jenkinsci/embeddable-build-status-plugin#27]
Please, make new release to allow users use latest changes in plugin like text endpoint.

**Comment by JohnStratoudakis** [comment]
Hi, when is the expected release date?

And how can I contribute? Any specific list of issues, bugs, or testing that needs to be done?

**Comment by thomas-dee** [comment]
@JohnStratoudakis The release is planned for the end of this month (January 2019). I'm thinking about releasing a beta version first so that you (and all others) can test that major overhaul.

**Comment by thomas-dee** [comment]
I just released v2.0-beta1. Please see [here](https://jenkins.io/doc/developer/publishing/releasing-experimental-updates) on how to install them.

**Comment by thomas-dee** [comment]
If there are no issues with this beta1 or there is no feedback I will release the final v2.0 at the end of January.

So it would be nice if you'd give some feedback.

**Comment by prolificcoder** [comment]
Hello, I just started using this beta and it is looking promising.

I am trying embed the status of the build into **confluence** and the custom text and custom status with
```?subject=Custom Text&status=My passing text``` worked for me

But when I try to use the variables like (${displayName}) in subject, confluence is panicking and just showing wiki markup, I get 
```Unknown macro: {displayName}```

Also i get a similar error when trying to use the branch selector with :`${params.BRANCH=master}`

Is it something that we have to ask confluence folks? An example of where you are all using these parameters would be great.  (is it GitHub only?) 

BTW, thanks for working on this, it looks outdated and your initiative is bringing back more use cases.

**Comment by prolificcoder** [comment]
Actually I experimented with the same in GitHub.com (private instance) and got the desired result
![image](https://user-images.githubusercontent.com/149176/51564883-51796e00-1e45-11e9-900c-10da782ef8e1.png)

Looks like its a problem on confluence side

**Comment by prolificcoder** [comment]
Alright scratch my comment above, figured out how to trick confluence by using Markup and encoding ```${duration}``` to ```%24%7Bduration%7D```

**Comment by thomas-dee** [comment]
@prolificcoder Thank you for the feedback. Have you any suggestions for a documentation about this?

**Comment by prolificcoder** [comment]
@thomas-dee I was trying to make use of this plugin to publish code coverage numbers, which I already have as jenkins variable in Jenkinsfile. Is there a way for doing this?

I was looking at DSL and `addEmbeddableBadgeConfiguration` but do we need provide it with a build id? what is it going to be? That's the part not entirely clear to me. 
Also in your documentation i see that you got the build badges based on this configuration but not clear on should we add something Readme.md to make that possible?

**Comment by thomas-dee** [comment]
No, you do not need to provide a build id. The **id** argument for `addEmbeddableBadgeConfiguration` is any unique id you can later reference using the `buildStatus/icon?config=<id>` customization.

**Comment by prolificcoder** [comment]
Hmm.. I am trying like you mentioned but it doesn't seem to have any affect on the badge that is showing up in readme.md

**Comment by thomas-dee** [comment]
>Hmm.. I am trying like you mentioned but it doesn't seem to have any affect on the badge that is showing up in readme.md  ...

@prolificcoder What does your badge url look like?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thomas-dee** [comment]
You need to reference the badge configuration using the id `androidBuildBadge` as `config` query parameter:

E.g.: `http://<jenkins-root-url>/.../badge/icon?config=androidBuildBadge`

**Comment by prolificcoder** [comment]
[![Build Status](https://jenkins.go.int.godaddy.com/buildStatus/icon?config=androidBuildBadge)]

**Comment by thomas-dee** [comment]
The `config` parameter references a badge configuration in terms of appearance not in terms of build selection.

If you use the unprotected URL (`.../buildStatus/icon?...`) you need to select the specific build via the `job` and `build` parameters. Please see [README.md](https://github.com/jenkinsci/embeddable-build-status-plugin#job) on how to use them.

`https://jenkins.go.int.godaddy.com/buildStatus/icon?job=...&build=...&config=androidBuildBadge`

**Comment by ajaybgupta** [comment]
Any update on the release? It was supposed to be done by 14 Feb 2019.

**Comment by thomas-dee** [comment]
>Any update on the release? It was supposed to be done by 14 Feb 2019.

@ajaybgupta Sorry. The next „flu release“ cropped up. I guess the release will happen next week.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ajaybgupta** [comment]
Thanks @thomas-dee for the information.

**Comment by thomas-dee** [comment]
v2.0 released
