### ISSUE TITLE
Error HTTP 404 for unprotected link

### ISSUE THREAD

**Issue by stephanebouchard** [jenkinsci/embeddable-build-status-plugin#28]
# Error HTTP 404 for unprotected link

I get the **Error HTTP 404** when trying to get the unprotected link Build Status Icon. It happened on all  my "GitHub Organization" and "Multibranch Pipeline" Jenkins Projects **with** branches containing **'/'** in their name. For example if the branch name is `release/1.2.8`

Here is my Jenkins Setup for the explanation of this issue.

- GitHub Organization (**oss**)
- contain the repository (**zlib**)
- with two branches: `master` and `release/1.2.8`

The links provided by the plugin are:

`master`

- https://jenkins.example.com/buildStatus/icon?job=oss/zlib/master

`release/1.2.8`

- https://jenkins.example.com/buildStatus/icon?job=oss/zlib/release%2F1.2.8

## Results

- As expected, the Build Status Icon is displayed for `master` branch.

But **not** for the `release/1.2.8` branch. This is the error message when trying to access the link with my web browser:

```
This jenkins.example.com page can’t be found
No webpage was found for the web address: https://jenkins.example.com/buildStatus/icon?job=oss/zlib/release%2F1.2.8
HTTP ERROR 404
```

**Comment by koeberlue** [comment]
I think you have to replace `/` with `%3A` in the job name

**Comment by thomas-dee** [comment]
Branches with slashes are internally stored in Jenkins already encoded (like `release%2F1.2.8`).
To reference the correct job you MUST encode the branch name **twice**: `release%252F1.2.8`.
So, a working url would be: `https://jenkins.example.com/buildStatus/icon?job=oss/zlib/release%252F1.2.8`

**Comment by thomas-dee** [comment]
v2.0 released

**Comment by geminixandroid** [comment]
also trying to figure out escaping slashes, created a simple redirection service that does the escaping
https://github.com/geminixandroid/jenkins-badge-redirect
