### ISSUE TITLE
Build url is wrong

### ISSUE THREAD

**Issue by FLasH3r** [jenkinsci/embeddable-build-status-plugin#41]
I haven't setup a domain for my Jenkins - the ip is internal instead of the external

![image](https://user-images.githubusercontent.com/1413249/55109125-bf5c4300-50dd-11e9-9b54-a4cac23cea46.png)

**Comment by thomas-dee** [comment]
Hi @FLasH3r,

What is your "Jenkins URL" setting in the global configuration pane?

Greetings,
Thomas
