### ISSUE TITLE
Broken image in github

### ISSUE THREAD

**Issue by tjmoore** [jenkinsci/embeddable-build-status-plugin#43]
I have a simple build status link in my readme.md to our local Jenkins server. If I preview readme.md in a Markdown viewer in VS Code, it renders fine. I also have a link on a Confluence page, and that renders fine.

In GitHub however it fails to render, only showing a broken image.

The link is very simple, of this format...

`[![Build Status](http://jenkins-server:8080/buildStatus/icon?job=our-project%2Fmaster)](http://jenkins-server:8080/blue/organizations/jenkins/our-project/activity?branch=master)`

I have also tried with simple HTML 'img' tags, but doesn't work.

If I put the image link direct into the browser it renders fine.

I should add that we're using GitHub Enterprise, hosted on-premises but then it can see our Jenkins server, plus it works in our Confluence which is cloud hosted (i.e. the browser can see the Jenkins server so works fine).

**Comment by jefersonchaves** [comment]
I'm facing a similar issue and it seems to be related to update recently.

**Comment by xinatcg** [comment]
same issue. I have checked the GitHub camo troubleshooting: https://help.github.com/en/articles/about-anonymized-image-urls. The image should be no problem.

**Comment by prasanna-sk** [comment]
Same issue - brken images rendered on README.md - but, when clicked on the link, the browser renders the image just fine. 
Any workarounds?

**Comment by deersilverstein** [comment]
Also seeing this issue

**Comment by bhorwood** [comment]
It looks like this plugin outputs the build status as HTML and not an image. This explains why image markdown isn't working.

Any chance this plug can be updated to output an image resource?

**Comment by dblbirdie** [comment]
GitHub proxies every image by its own servers. That's why it must be publicly available:
[Viewing images on private networks](https://help.github.com/en/github/authenticating-to-github/about-anonymized-image-urls#viewing-images-on-private-networks)

Any ideas how to bypass this?

**Comment by tjmoore** [comment]
> GitHub proxies every image by its own servers. That's why it must be publicly available:
> [Viewing images on private networks](https://help.github.com/en/github/authenticating-to-github/about-anonymized-image-urls#viewing-images-on-private-networks)

It makes sense with public GitHub if it can't see the private network, but that shouldn't apply in my case because we're using GitHub Enterprise which is on-premises and has full visbility of the image on a server in the same LAN.

**Comment by tjmoore** [comment]
Ah, I think this is the issue. The image is being hosted on HTTP and GitHub enterprise instance is running HTTPS. That will break. Sure enough debug console in the browser shows an error due to mismatch of protocol for the image.

https://stackoverflow.com/a/47526427/219645

As I understand it with public GitHub, that was what the Camo proxy is doing. It makes insecure images secure so this error goes away. With on-premises versions of GitHub Enterprise this isn't available (or is it an option?).

I'll see if I can get an SSL cert for the internal Jenkins server and see if that fixes it.

**Comment by jefersonchaves** [comment]
@tjmoore : have you checked if the server has the correct certificates? This was the issue I faced many moons ago.

**Comment by tjmoore** [comment]
@jefersonchaves - it's just a case of the Jenkins server has no cert at all as it's hosting on HTTP. GitHub server cert is fine. Will need to speak with IT to get a cert for Jenkins though.

Still slightly odd that cloud Confluence (public, HTTPS) is loading the image in the browser from the internal Jenkins (private HTTP) however. So long as browser computer is on the LAN or VPN of course. With GitHub I get the mixed content error.

**Comment by jefersonchaves** [comment]
@tjmoore - That is more or less what happened to me: the Jenkins certificate chain was not complete and GitHub was failing to load the image. Once I fixed the certificate in Jenkins then it started to work again.

**Comment by SangaviJayagopi** [comment]
I am facing the problem where the image is broken in my GitHub private repo. 

@jefersonchaves How to set up the certificate in Jenkins?

**Comment by jefersonchaves** [comment]
@SangaviJayagopi : that really depends, I recommend you looking at [Jenkins manual](https://www.jenkins.io/doc/book/installing/#configuring-http). But in my case it was [nginx](https://wiki.jenkins.io/plugins/servlet/mobile?contentId=66847445#content/view/66847445). For both there are good articles available in the internet.

**Comment by slw07g** [comment]
I was having issues as well, but with HTTPS, and had a ton of trouble trouble-shooting. Leaving this comment in case others searching for help encounter the same problem.

I use LetsEncrypt certs for my nginx reverse proxy, but I was not using the full chain certificate `fullchain1.pem`. So, once I updated my nginx reverse proxy configuration to use the fullchain cert instead of `cert1.pem`, it resolved the issue for me. 

This implies that github camo proxy requires images hosted on HTTPS servers to have a fully valid CA chain.

**Comment by spetrov** [comment]
@slw07g Thanks for pointing this out! I was pulling my hair for quite a while... This solved my problem too!

**Comment by rkeithhill** [comment]
We ran into this when we upgraded our on-prem Bitbucket server, switching it https.  Our Jenkins master is still HTTP.  [This flags tweak ](https://stackoverflow.com/a/53388534) in Edge (substitute `edge://` for `chrome://`) did the trick for me:

**Comment by MarkEWaite** [comment]
Closing this issue because the solution seems to be to serve Jenkins with https so that the https access from other servers also uses https for the build status.
