### ISSUE TITLE
Plain link url to job should be linked to job url by default

### ISSUE THREAD

**Issue by MonsieurRoZz** [jenkinsci/embeddable-build-status-plugin#56]
Hello there,
thanks a lot for this great tool.

Current version allow usage of clickable links.
It works well if I am using a "config" whiting a pipeline.

I am currently also using plain link (protected and unprotected) for my build statuses:
https://{jenkins_root}/job/Tests/job/{job_name}/badge/icon
https://{jenkins_root}/buildStatus/icon?job={job_name}

When I use these link into a wiki page and currently I do not have the possibility to click.
**In my opinion, url link to job should be available by default.**

**Comment by MarkEWaite** [comment]
This really can't be done without you adding additional wiki markup to the text you are inserting in your wiki page.  The ending text `/badge/icon` is used by the wiki page generator (Confluence, XWiki etc.) to create a hyperlink.  The URL of the icon is the source of the image.  It cannot also be a link to another location
