### ISSUE TITLE
Please add .adoc snippets

### ISSUE THREAD

**Issue by mcascone** [jenkinsci/embeddable-build-status-plugin#59]
I love that you provide pre-configured code in various formats to embed the badges in our pages. 
I've started using the `.adoc` format for readmes and would love to have that syntax ready-made instead of having to re-format it (which I'm still figuring out).
Thanks!

**Comment by MarkEWaite** [comment]
See the adoc files in the www.jenkins.io source code for possible examples

**Comment by MarkEWaite** [comment]
Fixed by #222
