### ISSUE TITLE
Question: setup badge width

### ISSUE THREAD

**Issue by fannw** [jenkinsci/embeddable-build-status-plugin#67]
Thanks for create a great plugin, is there any way to set the badge width?
![image](https://user-images.githubusercontent.com/80095051/120479297-5d47a880-c3e0-11eb-9c56-2d9bd06cd270.png)

**Comment by gregallen** [comment]
I think this is actually a new new bug - the automatic width it not working anymore

**Comment by CalvinWilkinson** [comment]
My github action badges are not auto sizing either.  The text is being cut off.

![image](https://user-images.githubusercontent.com/85414302/128865313-95186424-9df7-408e-9dbe-e0ba5dd365c7.png)

**Comment by MarkEWaite** [comment]
I'm not seeing that issue on the current plugin.  Some examples include:

### Protected
[![Build Status](https://ci.jenkins.io/job/Plugins/job/embeddable-build-status-plugin/job/master/badge/icon?subject=Very%20long%20descriiption%20text%20inserted%20here&status=also%20a%20%long%20status%inserted%20here)](https://ci.jenkins.io/job/Plugins/job/embeddable-build-status-plugin/job/master/)

### Unprotected
[![Build Status](https://ci.jenkins.io/buildStatus/icon?job=Plugins%2Fembeddable-build-status-plugin%2Fmaster?subject=Very%20long%20subject%20descriiption%20text%20inserted%20here&status=also%20a%20%long%20status%inserted%20here)](https://ci.jenkins.io/job/Plugins/job/embeddable-build-status-plugin/job/master/)
