### ISSUE TITLE
builtin variables "description" does not get value

### ISSUE THREAD

**Issue by djwgit** [jenkinsci/embeddable-build-status-plugin#75]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

- macOS 12.3
- Jenkins 2.341

### Reproduction steps

trying to use the builtin variables in a url, 
buildId, buildNumber, displayName, description, duration, and startTime

this works:
http://name.server.com:8080/job/JobName/22/badge/icon?subject=XCTest&status=${displayName}
http://name.server.com:8080/job/JobName/badge/icon?subject=XCTest&status=${displayName}

this does not work using `description`
http://name.server.com:8080/job/JobName/22/badge/icon?subject=XCTest&status=${description}
http://name.server.com:8080/job/JobName/badge/icon?subject=XCTest&status=${description}

I searched the code, seems it is correct there, 
https://github.com/jenkinsci/embeddable-build-status-plugin/blob/c440049bacd4813b558981b99b600db9e0c491bb/src/main/java/org/jenkinsci/plugins/badge/extensions/SpecialValueParameterResolverExtension.java#L44
but why it failed to get the description for the task run... 

thanks !

### Expected Results

a task run has description set after the task complete, say "122 tests failed", 
expecting the badge will be  `[XCTest: 122 tests failed]`

### Actual Results

now it shows as `[XCTest: description]`

**Comment by MarkEWaite** [comment]
I can't duplicate the issue.  The build description "aa-Tests passed-bb" is placed as the subject in this example with `subject=aa-${description}-bb`:

[![Build Status](https://ci.jenkins.io/job/Plugins/job/embeddable-build-status-plugin/job/master/70/badge/icon?subject=aa-${description}-bb)](https://ci.jenkins.io/job/Plugins/job/embeddable-build-status-plugin/job/master/70/)
