### ISSUE TITLE
Update appears to have broken github readme links displaying "not run"

### ISSUE THREAD

**Issue by MegaMech** [jenkinsci/embeddable-build-status-plugin#81]
Badges no longer display correctly in the mk64 decomp repo readme. It says "not run" instead of showing the percentage decomped.

It appears the plugin was recently updated to v2.0.4 (released five days ago).
The repo has not modified the links or the build system in-charge of producing the badges
If I manually go to the links in the readme the badges display correctly.

https://github.com/n64decomp/mk64

Links are formatted as such:
```
[![Build Status](https://ci.valandil.ca/buildStatus/icon?job=mk64%2Fmaster&config=codeProgress)](https://ci.valandil.ca/job/mk64/job/master/)
```

**Comment by shahar-h** [comment]
@MegaMech I also have this issue, how did you managed to solve it?

**Comment by shahar-h** [comment]
Solved by granting `ViewStatus` permission to anonymous users.
